### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by Mikej81**

### CODE REVIEW

**Comment by Yaredt** [comment]
MIke,
The new version of SACA seems a lot simpler to understand and implement. how do you recommend implementing the break and inspect requirement on the SACA? 
thank you

**Comment by Mikej81** [comment]
@Yaredt , Are you talking forward or reverse?  There are some features I am working on implementing / automating, but that is one that might require some end user customizations.

One of the items I have added is automatically importing the DOD Root CA's, so the bundle is deployed on bootstrap, but there isn't a way to generate trusted certs for government. 

If you are referring to the old firewall sandwich architecture, that is coming as well, I just need some time to get it built out.

**Comment by Yaredt** [comment]
@Mikej81  comparing the V1 and V2. V2 is easy to understand especially for someone who is not F5 expert. 

The requirement calls for inspection of both traffic (incoming and outgoing). Yes, It would be nice to have the IPS implementation.

Thank you for adding the DoD Root CA, we have used PowerShell DSC to add the certs on Windows machine. We have also provided a certificate by the gov for our application.

Our customer wants to use only PAYG option. Can I fork this code and start working on that? Is there any functional limitation for using PAYG?

Thank you

**Comment by Mikej81** [comment]
Sure.  Go for it.  I plan to work on the 2 tier system soon, still working on getting a lot of the hardening configurations implemented and will dig back in on the other use cases.

**Pull request merged**
